model:
  class_path: project.pl_models.lstm_model.LSTMPL
  init_args:
    num_hidden: 64
    num_layers: 2
    dropout: 0.1
    static_dropout: 0.1
    num_meteo_enc: 16
    num_geofactors_enc: 3
data:
  batch_size: 50
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.001
    weight_decay: 0.001