model:
  class_path: project.pl_models.tcn_model.TemporalConvNetPL
  init_args:
    num_hidden: 32
    num_layers: 1
    dropout: 0.1
    static_dropout: 0.1
    kernel_size: 6
data:
  batch_size: 50
  chunk_buffer_size: 10
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.0001
    weight_decay: 0.001