seed_everything: 99
data:
  fold_id: 0
  target_daily:
    - 'fvc'
    - 'fvc_ano'
  batch_size: 24
  chunk_buffer_size: 4
  num_queue_workers: 12
trainer:
  accelerator: 'gpu'
  devices:
    - 0
  num_sanity_val_steps: 0
  log_every_n_steps: 1
  val_check_interval: 0.1
  accumulate_grad_batches: 5
  max_epochs: 100
  num_nodes: 1
  detect_anomaly: false
  callbacks:
    - class_path: utils.pl_utils.OutputWriter
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: 'val_loss'
        patience: 20
        min_delta: 0.0
        mode: 'min'
    - class_path: pytorch_lightning.callbacks.TQDMProgressBar
      init_args:
        refresh_rate: 100
  logger:
    class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      save_dir: null
      version: null
  plugins:
    - class_path: pytorch_lightning.plugins.environments.SLURMEnvironment
      init_args:
        auto_requeue: false
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.0001
    weight_decay: 0.0
