model:
  class_path: project.pl_models.lstm_model.LSTMPL
  init_args:
    num_outputs: 2
    num_hidden: 128
    num_layers: 3
    dropout: 0.0
    static_dropout: 0.0
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.001
    weight_decay: 0.0
